### PR TITLE
test: adds doctest execution to the existing examples

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #13 

That's what I have locally:

```
» pytest --doctest-modules
================================ test session starts =================================
platform darwin -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/sobolev/Documents/github/punq, inifile:
plugins: cov-2.6.1
collected 23 items

punq/__init__.py F..F                                                          [ 17%]
tests/test_chain_dependencies.py .                                             [ 21%]
tests/test_instance_creation.py ..............                                 [ 82%]
tests/test_list_resolution.py .                                                [ 86%]
tests/test_string_annotations.py ...                                           [100%]

====================================== FAILURES ======================================
__________________ [doctest] punq.InvalidForwardReferenceException ___________________
030         When we try to inspect the constructor for the service we fail with an
031         InvalidForwardReferenceException
032
033         >>> from dataclasses import dataclass
034         >>> from punq import Container
035         >>> @dataclass
036         ... class Client:
037         ...     dep: 'Dependency'
038         >>> container = Container()
039         >>> container.register(Client)
Differences (unified diff with -expected +actual):
    @@ -1,11 +1,28 @@
     Traceback (most recent call last):
    -File "<stdin>", line 1, in <module>
    -File "__init__.py", line 195, in register
    -  self.registrations.register(service, factory, instance, **kwargs)
    -File "__init__.py", line 139, in register
    -  self.register_concrete_service(service)
    -File "__init__.py", line 121, in register_concrete_service
    -  Registration(service, service, self._get_needs_for_ctor(service), {})
    -File "__init__.py", line 53, in _get_needs_for_ctor
    -  raise InvalidForwardReferenceException(str(e))
    +  File "/Users/sobolev/Documents/github/punq/punq/__init__.py", line 104, in _get_needs_for_ctor
    +    return typing.get_type_hints(cls.__init__, None, self._localns)
    +  File "/Users/sobolev/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 1001, in get_type_hints
    +    value = _eval_type(value, globalns, localns)
    +  File "/Users/sobolev/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 260,in _eval_type
    +    return t._evaluate(globalns, localns)
    +  File "/Users/sobolev/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 464,in _evaluate
    +    eval(self.__forward_code__, globalns, localns),
    +  File "<string>", line 1, in <module>
    +NameError: name 'Dependency' is not defined
    +<BLANKLINE>
    +During handling of the above exception, another exception occurred:
    +<BLANKLINE>
    +Traceback (most recent call last):
    +  File "/Users/sobolev/.pyenv/versions/3.7.1/lib/python3.7/doctest.py", line 1329, in __run
    +    compileflags, 1), test.globs)
    +  File "<doctest punq.InvalidForwardReferenceException[4]>", line 1, in <module>
    +    container.register(Client)
    +  File "/Users/sobolev/Documents/github/punq/punq/__init__.py", line 265, in register
    +    self.registrations.register(service, factory, instance, **kwargs)
    +  File "/Users/sobolev/Documents/github/punq/punq/__init__.py", line 207, in register
    +    self.register_concrete_service(service)
    +  File "/Users/sobolev/Documents/github/punq/punq/__init__.py", line 183, in register_concrete_service
    +    Registration(service, service, self._get_needs_for_ctor(service), {})
    +  File "/Users/sobolev/Documents/github/punq/punq/__init__.py", line 106, in _get_needs_for_ctor
    +    raise InvalidForwardReferenceException(str(e))
     punq.InvalidForwardReferenceException: name 'Dependency' is not defined

/Users/sobolev/Documents/github/punq/punq/__init__.py:39: DocTestFailure
_______________ [doctest] punq.Registry.register_service_and_instance ________________
138
139         Examples:
140             If we have an object that is expensive to construct, or that
141             wraps a resource that must not be shared, we might choose to
142             use a singleton instance.
143
144             >>> class DataAccessLayer:
145             ...     pass
146             ...
147             >>> class SqlAlchemyDataAccessLayer(DataAccessLayer):
UNEXPECTED EXCEPTION: NameError("name 'SQLAlchemy' is not defined")
Traceback (most recent call last):

  File "/Users/sobolev/.pyenv/versions/3.7.1/lib/python3.7/doctest.py", line 1329, in__run
    compileflags, 1), test.globs)

  File "<doctest punq.Registry.register_service_and_instance[1]>", line 1, in <module>

  File "<doctest punq.Registry.register_service_and_instance[1]>", line 2, in SqlAlchemyDataAccessLayer

NameError: name 'SQLAlchemy' is not defined

/Users/sobolev/Documents/github/punq/punq/__init__.py:147: UnexpectedException
======================== 2 failed, 21 passed in 0.21 seconds =========================

```

Now I need to resolve these global deps.

@bobthemighty do you like this approach?

### CODE REVIEW

**Comment by bobthemighty** [comment]
@sobolevn if you can make it work, I'd be happy to accept the PR!

I've never used doctest before. How do you handle stupid things like filepaths not matching?

**Comment by sobolevn** [comment]
🎉 

```
» pytest --doctest-modules -p tests.doctest_namespace
================================ test session starts =================================
platform darwin -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/sobolev/Documents/github/punq, inifile:
plugins: cov-2.6.1
collected 23 items

punq/__init__.py ....                                                          [ 17%]
tests/test_chain_dependencies.py .                                             [ 21%]
tests/test_instance_creation.py ..............                                 [ 82%]
tests/test_list_resolution.py .                                                [ 86%]
tests/test_string_annotations.py ...                                           [100%]

============================= 23 passed in 0.19 seconds ==============================

```

**Comment by sobolevn** [comment]
@bobthemighty I love doctests. We even have a policy in our company to tests pure functions with doctests only. 

docstests use `...` to ignore things that can be changed: instance ids, path, traceback details, etc.
We also need a custom `pytest` plugin called `test.doctest_namespace` so our `SQLAlchemy` example will work.

**Comment by bobthemighty** [comment]
@sobolevn can you confirm this is no longer WIP? If so I'll merge. I do have the beginnings of a PR for #2 which I'll push up and we can discuss how to fix that.

Do you have preferences on how to manage documentation?

**Comment by sobolevn** [comment]
Yes, this is a fully working PR.

**Comment by sobolevn** [comment]
@bobthemighty I use `readthedocs.org` and `sphinx`. It proved to be very reliable and easy.
Examples:
- https://wemake-python-styleguide.readthedocs.io/en/latest/

**Pull request merged**
